# Generated by Django 5.2.3 on 2025-08-25 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_snippet_mainapp_sni_name_48c470_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['user', 'name', 'lang'], name='MainApp_sni_user_id_2c247a_idx'),
        ),
    ]
